### ISSUE TITLE
It literally will instantly ban you 

### ISSUE THREAD

**Issue by Githubman6996** [blooketdevs/Blooket-Infinite-Tokens#1]
Bruh I don’t even need to test it

**Comment by blooketdevs** [comment]
SHUT UP NIGGER

**Comment by Githubman6996** [comment]
Quit EDITING MY REPLIES DUMBASS

**Comment by CryptoDude3** [comment]
yea this script is the best I used it on my friends account as his birthday present

**Comment by Githubman6996** [comment]
I ALREADY REPORTED YOU SO QUIT FUCKING EDITING MY REPLIES

**Comment by CryptoDude3** [comment]
> I ALREADY REPORTED YOU SO QUIT FUCKING EDITING MY REPLIES

fr

**Comment by 3ligma** [comment]
bro why are you editing comments

**Comment by CryptoDude3** [comment]
totally didn't write this script to troll skids so their accounts get banned

**Comment by 3ligma** [comment]
> totally didn't write this script to troll skids so their accounts get banned

fr

**Comment by DannyDan0167** [comment]
there is literally something wrong with you

**Comment by Githubman6996** [comment]
![IMG_9661](https://github.com/blooketdevs/Blooket-Infinite-Tokens/assets/144396091/0a595a3b-5393-462f-835e-43abfc8f2b1d)

**Comment by Githubman6996** [comment]
![IMG_9656](https://github.com/blooketdevs/Blooket-Infinite-Tokens/assets/144396091/53fb0b9a-0b4e-4e25-9f3d-dd252153345f)

**Comment by Githubman6996** [comment]
![IMG_9656](https://github.com/blooketdevs/Blooket-Infinite-Tokens/assets/144396091/865ffb08-9a22-4942-92c6-02f73346cf59)

**Comment by 3ligma** [comment]
> Bro I see the edits

same no need to hide

**Comment by 3ligma** [comment]
![image](https://github.com/blooketdevs/Blooket-Infinite-Tokens/assets/172942451/fe6b0a46-7e6b-4781-a887-113a7524ec09)

**Comment by 3ligma** [comment]
who gave bro the pass

**Comment by 3ligma** [comment]
if you use this you get banned

**Comment by 3ligma** [comment]
if you use this you get banned

**Comment by genericexists** [comment]
![image](https://github.com/blooketdevs/Blooket-Infinite-Tokens/assets/168141409/7baf39a6-654a-41d8-9b44-8a4cbf7adc95)
![image](https://github.com/blooketdevs/Blooket-Infinite-Tokens/assets/168141409/d57e8d04-1a64-4aa1-9527-e053841ced24)

**Comment by 3ligma** [comment]
![image](https://github.com/blooketdevs/Blooket-Infinite-Tokens/assets/172942451/4cfa7787-3fc5-4427-9098-9102347d5e32)
